version: "3"

services:
  app:
    build: .
    hostname: app
    container_name: app
    ports:
      - 3001:3000
  mongo:
    image: mongo
    hostname: mongo
    container_name: mongo
    ports:
      - "27017:27017"