version: "3"

services:
  app:
    # build: .
    image: akenisocean/node-js-mon-user:v0.0.1
    hostname: app
    container_name: app
    depends_on:
      - mongo
    ports:
      - 3001:3000
  mongo:
    image: mongo
    hostname: mongo
    container_name: mongo
    ports:
      - "27017:27017"